# PANA PAA用クライアント設定
client pana-paa {
    ipaddr = 127.0.0.1
    secret = testing123
    require_message_authenticator = no
    shortname = pana-paa
}

# ローカルホスト（テスト用）
client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    require_message_authenticator = no
    nas_type = other
}
